parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
  
plugins:
  - react

extends:
  - plugin:react/recommended
  - eslint:recommended

env:
  browser: true
  es2021: true
  node: true

rules:
  import/extensions: 0
  import/no-unresolved: 0
  react/prop-types: 0
  no-console: 0
  react-hooks/exhaustive-deps: 0
  react/jsx-no-constructed-context-values: 0
  react/function-component-definition: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }]
